### ISSUE TITLE
Pull Request: usare i file localmente in npm scripts

### ISSUE THREAD

**Issue by codekraft-studio** [GiuseppeCoretti/angular2-starter-webpack#1]
Ciao! Volevo dirti che sarebbe meglio chiamare i file localmente negli script di npm:

**Prima:**
```javascript
"scripts": {
    "build": "webpack --progress",
    "build:prod": "webpack -p --progress",
    "postinstall": "typings install",
    "serve": "webpack-dev-server --inline --progress"
  }
```

**Dopo:**
```javascript
"scripts": {
    "build": "node node_modules/webpack/bin/webpack --progress",
    "build:prod": "node node_modules/webpack/bin/webpack -p --progress",
    "postinstall": "node node_modules/typings/dist/bin install",
    "serve": "node node_modules/webpack-dev-server/bin/webpack-dev-server --inline --progress"
  },
```

La installazione (a me) è fallita perchè lo script di `postinstall` prevedeva che io avessi typings installato globalmente, cosa che non ho.

Quando si installano le dependencies con `npm install` i file vengono scaricati localmente nella cartella del progetto quindi ha senso usarli, sia perchè occupano spazio sia perchè non è detto che le persone abbiano i moduli globali.
Si potrebbe fare [npm link](https://docs.npmjs.com/cli/link) per creare dei symbolic link al modulo globale, ma spesso non è detto che le persone abbiano quei moduli installati globalmente.

**Comment by GiuseppeCoretti** [comment]
Grazie per il suggerimento. Effettivamente è stata proprio una svista la mia, avevo molti di quei pacchetti installati globalmente quindi in quel momento non lo avevo notato.

**Comment by codekraft-studio** [comment]
sostanzialmente me ne sono accorto perchè non avendo typings installato globalmente mi aveva fallito il postinstall, sennò non ci avrei fatto caso, però così è anti-errore almeno

**PS:** quando fai commit puoi specificare `#Fix 1` o uno di [questi](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) per chiudere in automatico l'issue
